### PR TITLE
Diversity in intro

### PR DESCRIPTION
**Pull request by JeffCarver**
Addresses #86

### CODE REVIEW

**Comment by karthik** [comment]
@JeffCarver This PR has been around for a while. Should I just merge this? Was the text incorporated into another commit?

**Comment by JeffCarver** [comment]
Yes I think it has been waiting on someone to approve and merge it. Maybe I didn't tag it correctly. Sorry about that. I think @danielskatz added something to my change, so I wasn't sure who needed to merge.

**Comment by danielskatz** [comment]
@karthik, I think you asked for a PR for this, so at least for me, I felt I did what you asked and was waiting for you to review it and merge it

**Comment by karthik** [comment]
Ok I'll review and merge.

**Pull request merged**
