### PR TITLE
Woven diversity

### PR DESCRIPTION
**Pull request by danielskatz**
This PR tries to add diversity to a number of areas where it was not explicit

The figure of the team in chapter 8 will need to be updated to include the diversity officer

### CODE REVIEW

**Comment by danielskatz** [comment]
If merged, this might address (or start to) #100

**Comment by JeffCarver** [comment]
@danielskatz the change in education looks good. The 25% figure is a good target. Would it be worth including the percentage of attendees from underrepresented groups from our Winter School as evidence of what we've done?

**Comment by karthik** [comment]
What is the rationale for 25%?

**Comment by danielskatz** [comment]
Trying to balance between achievable progress and something bigger. Feel free to suggest something else if you prefer.

**Comment by danielskatz** [comment]
> @danielskatz the change in education looks good. The 25% figure is a good target. Would it be worth including the percentage of attendees from underrepresented groups from our Winter School as evidence of what we've done?

What was that percentage?  If it goes anywhere, I would add it to 2.5

**Comment by JeffCarver** [comment]
I went back through the applications and calculated this information for those that attended (or at least are on our spreadsheet of final participants). We had 16 female and 13 male. 3 LGBTQ+ (one lists gender as female), 1 Latino male. I'm not sure how we want to report this information. So, if someone has the appropriate words, please help.

**Comment by karthik** [comment]
Im not entirely sure we should use this. We had no targets to begin with so it is a little odd to report post hoc.

**Comment by karthik** [comment]
> Trying to balance between achievable progress and something bigger. Feel free to suggest something else if you prefer.

Since we only have 4-5 fellows/year, we can strive to make sure 50% are from underrepresented groups, with 25% as the lower bound if we don't get enough applicants.  At least for fellows, I think this is easily achievable.

**Comment by danielskatz** [comment]
> > Trying to balance between achievable progress and something bigger. Feel free to suggest something else if you prefer.
> 
> Since we only have 4-5 fellows/year, we can strive to make sure 50% are from underrepresented groups, with 25% as the lower bound if we don't get enough applicants. At least for fellows, I think this is easily achievable.

Can you change/add that to this branch?

**Comment by JeffCarver** [comment]
> Im not entirely sure we should use this. We had no targets to begin with so it is a little odd to report post hoc.

Makes sense. Let's just leave it out then. I think the education text is fine.

**Comment by karthik** [comment]
> Can you change/add that to this branch?

Sure, is your branch up to date with master?

**Comment by danielskatz** [comment]
I believe so

**Comment by danielskatz** [comment]
other than the image you moved about 23 hours ago

**Comment by danielskatz** [comment]
@nniiicc - is this ok with you in terms of the change to the incubator section?

**Comment by nniiicc** [comment]
Yup - works for me

**Comment by danielskatz** [comment]
Thanks all - even though @sandragesing has not reviewed this, I am going to merge it with the idea that any individual changes can be rolled back.  I am doing this so that this PR doesn't get out of date and we can progress in these sections beyond it.  The main action that isn't done here that still should be is for @sandragesing to update the figure of the team in chapter 8 to include the diversity officer

**Pull request merged**
