### PR TITLE
Updates to introduction section on diversity

### LINKED ISSUE #11: Research on Open Source and Diversity
TODO item in paragraph that starts on line 99 of the introduction: 

I have some research in this direction and will look for some references and text to strengthen this bullet point. See Section II.B of this paper for some text that could potentially be adapted (http://carver.cs.ua.edu/Papers/Conference/2019/2019_ICSE_FLOSS-Gender.pdf)

### PR DESCRIPTION
**Pull request by JeffCarver**
Fixes #11

### CODE REVIEW

**Review by danielskatz — COMMENTED** [review]
this looks good to me

**Comment by danielskatz** [comment]
This is in a section @karthik wrote, so I've suggested he also review this, though it looks good to me.

**Review by karthik — COMMENTED** [review]
If these data are from self reported data via survey, we can avoid confusion by stating "1-5% of contributors to open source communities self identify as female" (to avoid the bad research practice of inferring gender from names).

**Comment by JeffCarver** [comment]
@karthik I made a slight modification to the wording and added a citation to my own paper that did ask the question about gender to the respondents.

**Pull request merged**
